name: 'Labels Action'
description: 'Wraps docker and docker-buildx to inject all GITHUB_* env vars as --label on every build'
runs:
  using: 'composite'
  steps:
    - name: Install labels shim into PATH
      shell: bash
      run: |
        SHIM_DIR="$HOME/labels-shim"
        mkdir -p "$SHIM_DIR"

        cp "$GITHUB_ACTION_PATH/entrypoint.sh" "$SHIM_DIR/docker"
        cp "$GITHUB_ACTION_PATH/entrypoint.sh" "$SHIM_DIR/docker-buildx"
        chmod +x "$SHIM_DIR/docker" "$SHIM_DIR/docker-buildx"

        echo "$SHIM_DIR" >> "$GITHUB_PATH"

        echo "[labels-action] shim installed in PATH; future docker commands will include labels"
